% -------------------------------------------------------------------
%  Generated by MATLAB on 31-Dec-2015 11:19:05
%  MATLAB version: 8.6.0.267246 (R2015b)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

output = saveVarsMat.output; % <50x32 single> too many elements

clear saveVarsMat;
